/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lzw.ui;

import com.lzw.daoImpl.OrderDaoImpl;
import com.lzw.entity.DD;
import com.lzw.entity.Order;

import java.util.Iterator;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author 绘梦
 */
public class CKDDUi extends javax.swing.JFrame {

    /**
     * Creates new form CKDDUi
     */
	javax.swing.table.DefaultTableModel mode = null;
    public CKDDUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("订单信息");

        jLabel6.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel6.setText("订单信息");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "订单号", "客户姓名", "客户电话", "经办人姓名", "经办人电话", "商品名", "商品数量", "价钱", "合计", "入库/出库", "日期"
            }
        ));
        	mode = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        
        while(mode.getRowCount()>0){
            mode.removeRow(mode.getRowCount()-1);//清除表数据
        }
        OrderDaoImpl odi = new OrderDaoImpl();
        List li1 = null;
        li1 = odi.findAll();
        Iterator<DD> it = li1.iterator();
        while(it.hasNext()){
            DD dd = it.next();
            mode.addRow(new Object[]{dd.getId(),dd.getcName(),dd.getcPhone(),dd.getwName(),dd.getwPhone(),dd.getgName(),dd.getNumber(),dd.getPrice(),dd.getAmount(),dd.getReason(),dd.getTime()});
        }

        jTable1.setRowHeight(23);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("查看条件：");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "所有订单", "入库", "出库", "经办人", "客户" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("查询");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("删除订单：");

        jButton2.setText("确定删除");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 506, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(497, 497, 497))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        OrderDaoImpl odi = new OrderDaoImpl();
        int id = Integer.parseInt(jTextField2.getText());
        Order or = odi.findOrderById(id);
        if(or==null){
            JOptionPane.showMessageDialog(null,"订单不存在！");
        }else{
            odi.removeOrder(or);
            JOptionPane.showMessageDialog(null,"删除成功！");
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String str = jTextField1.getText();
        String way = (String)jComboBox1.getSelectedItem();
        OrderDaoImpl odi = new OrderDaoImpl();
        switch(way){
            case "所有订单":
            	while(mode.getRowCount()>0){
                    mode.removeRow(mode.getRowCount()-1);//清除表数据
                }
                OrderDaoImpl odi2 = new OrderDaoImpl();
                List li1 = null;
                li1 = odi2.findAll();
                Iterator<DD> it = li1.iterator();
                while(it.hasNext()){
                    DD dd = it.next();
                    mode.addRow(new Object[]{dd.getId(),dd.getcName(),dd.getcPhone(),dd.getwName(),dd.getwPhone(),dd.getgName(),dd.getNumber(),dd.getPrice(),dd.getAmount(),dd.getReason(),dd.getTime()});
                }
                break;
            case "入库":
            	while(mode.getRowCount()>0){
                    mode.removeRow(mode.getRowCount()-1);//清除表数据
                }
               // OrderDaoImpl odi = new OrderDaoImpl();
                List li2 = null;
                li2 = odi.findIn();
                Iterator<DD> it2 = li2.iterator();
                while(it2.hasNext()){
                    DD dd = it2.next();
                    mode.addRow(new Object[]{dd.getId(),dd.getcName(),dd.getcPhone(),dd.getwName(),dd.getwPhone(),dd.getgName(),dd.getNumber(),dd.getPrice(),dd.getAmount(),dd.getReason(),dd.getTime()});
                }
                break;
            case "出库":
            	while(mode.getRowCount()>0){
                    mode.removeRow(mode.getRowCount()-1);//清除表数据
                }
                //OrderDaoImpl odi = new OrderDaoImpl();
                List li3 = null;
                li3 = odi.findOut();
                Iterator<DD> it3 = li3.iterator();
                while(it3.hasNext()){
                    DD dd = it3.next();
                    mode.addRow(new Object[]{dd.getId(),dd.getcName(),dd.getcPhone(),dd.getwName(),dd.getwPhone(),dd.getgName(),dd.getNumber(),dd.getPrice(),dd.getAmount(),dd.getReason(),dd.getTime()});
                }
                break;
            case "经办人":
            	while(mode.getRowCount()>0){
                    mode.removeRow(mode.getRowCount()-1);//清除表数据
                }
                //OrderDaoImpl odi = new OrderDaoImpl();
                List li4 = null;
                li4 = odi.findByWaiter(str);
                Iterator<DD> it4 = li4.iterator();
                while(it4.hasNext()){
                    DD dd = it4.next();
                    mode.addRow(new Object[]{dd.getId(),dd.getcName(),dd.getcPhone(),dd.getwName(),dd.getwPhone(),dd.getgName(),dd.getNumber(),dd.getPrice(),dd.getAmount(),dd.getReason(),dd.getTime()});
                }
                break;
            case "客户":
            	while(mode.getRowCount()>0){
                    mode.removeRow(mode.getRowCount()-1);//清除表数据
                }
               // OrderDaoImpl odi = new OrderDaoImpl();
                List li5 = null;
                li5 = odi.findByCustomer(str);
                Iterator<DD> it5 = li5.iterator();
                while(it5.hasNext()){
                    DD dd = it5.next();
                    mode.addRow(new Object[]{dd.getId(),dd.getcName(),dd.getcPhone(),dd.getwName(),dd.getwPhone(),dd.getgName(),dd.getNumber(),dd.getPrice(),dd.getAmount(),dd.getReason(),dd.getTime()});
                }
                break;
                
                
                
        }
            
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CKDDUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CKDDUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CKDDUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CKDDUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CKDDUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
