/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lzw.ui;

import java.util.Iterator;
import java.util.List;

import com.lzw.daoImpl.CustomerDaoImpl;
import com.lzw.entity.Customer;


/**
 *
 * @author 绘梦
 */
public class CKKHUi extends javax.swing.JFrame {

    /**
     * Creates new form CKKHUi
     */
	javax.swing.table.DefaultTableModel mode = null;
    public CKKHUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("客户信息");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "客户ID", "客户名", "联系人", "地址", "电话", "邮箱", "所欠金额", "银行卡号"
            }
        ));
        mode = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        
        while(mode.getRowCount()>0){
            mode.removeRow(mode.getRowCount()-1);//清除表数据
        }
        CustomerDaoImpl cdi = new CustomerDaoImpl();
        List li = null;
        li = cdi.findAll();
        Iterator<Customer> it = li.iterator();
        while(it.hasNext()){
            Customer cc = it.next();
            mode.addRow(new Object[]{cc.getcId(),cc.getcName(),cc.getcContacts(),cc.getcAdress(),cc.getcPhone(),cc.getcEmal(),cc.getcMoney(),cc.getcBackCard()});
        }
        
        
        
        
        jTable1.setRowHeight(30);
        jTable1.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("查询条件：");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "所有客户", "未还账", "ID" }));

        jButton1.setText("查询");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel6.setText("客户信息");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel6)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String str = jTextField1.getText();
        String way = (String)jComboBox1.getSelectedItem();
        switch(way){
        case "所有客户":
        	while(mode.getRowCount()>0){
                mode.removeRow(mode.getRowCount()-1);//清除表数据
            }
            CustomerDaoImpl cdi = new CustomerDaoImpl();
            List li = null;
            li = cdi.findAll();
            Iterator<Customer> it = li.iterator();
            while(it.hasNext()){
                Customer cc = it.next();
                mode.addRow(new Object[]{cc.getcId(),cc.getcName(),cc.getcContacts(),cc.getcAdress(),cc.getcPhone(),cc.getcEmal(),cc.getcMoney(),cc.getcBackCard()});
            }
            break;
        case "未还账":
        	while(mode.getRowCount()>0){
                mode.removeRow(mode.getRowCount()-1);//清除表数据
            }
            CustomerDaoImpl cdi2 = new CustomerDaoImpl();
            List li2 = null;
            li2 = cdi2.findQianzhang();
            Iterator<Customer> it2 = li2.iterator();
            while(it2.hasNext()){
                Customer cc = it2.next();
                mode.addRow(new Object[]{cc.getcId(),cc.getcName(),cc.getcContacts(),cc.getcAdress(),cc.getcPhone(),cc.getcEmal(),cc.getcMoney(),cc.getcBackCard()});
            }
            break;
        case "ID":
        	while(mode.getRowCount()>0){
                mode.removeRow(mode.getRowCount()-1);//清除表数据
            }
            CustomerDaoImpl cdi3 = new CustomerDaoImpl();
            
            	int str2 = Integer.parseInt(str);
                Customer cc = cdi3.findCustomerById(str2);
                mode.addRow(new Object[]{cc.getcId(),cc.getcName(),cc.getcContacts(),cc.getcAdress(),cc.getcPhone(),cc.getcEmal(),cc.getcMoney(),cc.getcBackCard()});
            }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CKKHUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CKKHUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CKKHUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CKKHUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CKKHUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
